### ISSUE TITLE
Create a decision document to decide on restructuring the site to deliver multiple views for each site

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/marquand-catalogs#20]
- [x] First create a [decision document](https://docs.google.com/document/d/12sp3b5Hm0E8EP-saxfKBYat2bYvD1OJ0d6GL4fNNWE8/edit).

**Comment by christinach** [comment]
Thank you @sandbergja 🍄 @rladdusaw 🐈‍⬛  and the rest of the team @maxkadel 🦄 @christinach 🐬 @Beck-Davis for reviewing this document.
